---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: prajit1999
  become: false
  tasks:
       - name: Pull Docker Image
         docker_image:
              name: "prajit1999/calculator"
              source: pull
         register: docker_pull_result

       - name: Display Docker Pull Result
         debug:
              var: docker_pull_result

       - name: Start Docker service
         service:
              name: docker
              state: started
       - name: Running container
         shell: docker run -it -d prajit1999/calculator
